apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wordpress
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: 'https://charts.bitnami.com/bitnami' 
    chart: wordpress
    targetRevision: 19.0.4
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            wordpressUsername: user
            wordpressEmail: wordpress_eks@example.com
            wordpressBlogName: wordpress_eks
            wordpressPassword: <path:prod/wordpress_eks#wordpress_user_password>

            mariadb:
              enabled: false

            service:
              type: ClusterIP

            externalDatabase:
              port: 3306
              host: <path:prod/wordpress_eks#db_endpoint>
              user: <path:prod/wordpress_eks#db_username>
              password: <path:prod/wordpress_eks#db_password>
              database: <path:prod/wordpress_eks#db_name>

            persistence:
              storageClass: ebs-gp2
              accessMode: ReadWriteOnce

            autoscaling:
              enabled: true
              maxReplicas: 5
              targetCPU: 50

            ingress:
              enabled: true
              ingressClassName: alb
              annotations:
                kubernetes.io/ingress.class: alb
                external-dns.alpha.kubernetes.io/hostname: <path:prod/wordpress_eks#domain_name>
                alb.ingress.kubernetes.io/target-type: ip
                alb.ingress.kubernetes.io/scheme: internet-facing
                alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
                alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
                alb.ingress.kubernetes.io/certificate-arn: <path:prod/wordpress_eks#acm_arn>
                alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
              
              hostname: <path:prod/wordpress_eks#domain_name>
              path: /*
              pathType: ImplementationSpecific

            livenessProbe:
              enabled: true
              initialDelaySeconds: 120
            readinessProbe:
              enabled: true
              initialDelaySeconds: 60

            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
                namespace: monitoring
                # interval: 1m
                labels:
                  release: prometheus


# values.yaml 사용하는것 불가능, 두 git repo를 사용하는데서 문제가 발생하는듯
# https://github.com/argoproj/argo-cd/issues/2789


# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: wordpress
# spec:
#   project: default
#   source:
#     repoURL: 'https://your.git.repo/url.git'  # The URL of your Git repository
#     path: path/to/kustomize/base  # The path within your repo where your Kustomize configuration is located
#     kustomize: {}
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: default
