apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
  argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: 'https://kubernetes-sigs.github.io/metrics-server/'
    chart: metrics-server
    targetRevision: 3.12.0
    helm:
      values: |
        metrics:
          enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus  
        
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi


