apiVersion: v3
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  type: LoadBalancer # This will provision an AWS ELB when used in EKS
  ports:
  - port: 80
  selector:
    app: wordpress
