name: deploy

on:
  push:
    branches:
      - main 


env:
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

jobs:
  terraform:
    name: terraform plan apply
    runs-on: ubuntu-latest
    # environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # defaults:
    #   run:
    #     shell: bash
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/env/prod

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform/env/prod

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform/env/prod


    