name: deploy

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'


jobs:
  terraform:
    name: deploy eks
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/env/prod

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform/env/prod

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
    #   working-directory: ./terraform/env/prod


    